### ISSUE TITLE
Property 'queryFormat' is missing

### ISSUE THREAD

**Issue by eamello** [phanxgames/phanx-mysql#1]
Hi there, I am getting the following error:

Types of property 'mysql' are incompatible.
    Property 'queryFormat' is missing in type '{ host: string; database: string; user: string; password: string; connectionLimit: number; }' but required in type 'IMysqlConfig'.

  node_modules/phanx-mysql/PhanxMysql.d.ts:386:5
    386     queryFormat: (query: string, values: any) => string;
            ~~~~~~~~~~~
    'queryFormat' is declared here.

My config.json file:

{
    "mysql": {
      "host": "localhost",
      "database": "XXX",
      "user": "XXX",
      "password": "XXX",
      "connectionLimit": 10
    },
    "usePool":true,
    "autoCloseMinutes":0,
    "useNamedParamsQueryFormat":true,
    "showDebugTraces": false
  }

**Comment by phanxgames** [comment]
Thank you for bringing this up. I will update the interface so the property is more properly reflected there.

**Comment by eamello** [comment]
Thanks Henry, please let me know when it's done then I can update my library.

I have created a BaseService class which I extend to all my service classes. The way I got around this issue was creating the IDbConfig object myself, creating also a query_format object. I didn't find a way to add the query_format property into my config.json file.

Find below my BaseService.ts:

import { DecodedUser } from '@src/services/auth';
import { UserLog } from './../models/user_log_model';
import dbConfig2 from '../../config/config.json';
import { IDbConfig, IMysqlConfig, PhanxMysql } from "phanx-mysql";
import logger from './../logger';
import moment from 'moment';
import { UserLogService } from './user_log_service';

export class BaseService {

    constructor() {

        const query_format = ((query:string,database:any) => "");

        const objIDbConfig: IDbConfig = {    "mysql": {
            "host": dbConfig2.mysql.host,
            "database": dbConfig2.mysql.database,
            "user": dbConfig2.mysql.user,
            "password": dbConfig2.mysql.password,
            "connectionLimit": dbConfig2.mysql.connectionLimit,
            "queryFormat": query_format  
          },
          "usePool": dbConfig2.usePool,
          "autoCloseMinutes": dbConfig2.autoCloseMinutes,
          "useNamedParamsQueryFormat": dbConfig2.useNamedParamsQueryFormat,
          "showDebugTraces": dbConfig2.showDebugTraces
        }

        PhanxMysql.config = objIDbConfig;   

        //optional:
        PhanxMysql.setAutoCloseMinutes(1);
    }

    protected db = new PhanxMysql();
    

    protected initiallize(): Promise<PhanxMysql>
    {
        return PhanxMysql.createAndStart();;
    }

    protected getKeyValuePairToUpdate(objClass: any, loggedUserId: number, privateKey1: string, privateKey2?: string): any
    {
        const now = moment(new Date()).format('YYYY-MM-DD HH:mm');
        const obj: {[key: string]: any} = { "updated_by": loggedUserId, "updated_on": now };  

       Object.keys(objClass).forEach((key: string) => { 
            if(key != privateKey1 && key != privateKey2 && key != "updated_by" && key != "updated_on" && objClass[key] != null && key!= "avatarBase64")
                obj[key] = objClass[key];
        });
        
        //logger.info(obj);

        return obj;
    } 
    
    protected getKeyValuePairToInsert(objClass: any, loggedUserId: number, privateKey1: string, privateKey2?: string): any
    {
        const now = moment(new Date()).format('YYYY-MM-DD HH:mm');
        const obj: {[key: string]: any} = { "created_by": loggedUserId, "created_on": now };  

       Object.keys(objClass).forEach((key: string) => { 

            if(privateKey1 && privateKey2) {
                if(key != "created_by" && key != "created_on")
                obj[key] = objClass[key];         
            }
            else if(privateKey1 && !privateKey2) {
                if(key != privateKey1 &&  key != privateKey2 && key != "created_by" && key != "created_on")
                    obj[key] = objClass[key]; 
            }
        });        

        return obj;
    }  

    protected insertLog(operation: string, description: string, location: string, entity_name: string, entity_id:number, decodedUser: DecodedUser): UserLog{
        const userLog = new UserLog()
        userLog.company_id = decodedUser.payload.company_id;
        userLog.company_name = decodedUser.payload.company_name;
        userLog.entity_name = entity_name;
        userLog.entity_id = entity_id;
        userLog.username = decodedUser.payload.email;
        userLog.name = decodedUser.payload.name;
        userLog.operation = operation;
        userLog.description = description;
        userLog.location = location;
        return userLog;
    }
}

My config.json:

{
    "mysql": {
      "host": "localhost",
      "database": "cloudbase_api",
      "user": "XXXXX",
      "password": "XXXXX",
      "connectionLimit": 10     
    },
    "usePool":true,
    "autoCloseMinutes":0,
    "useNamedParamsQueryFormat":true,
    "showDebugTraces": false
    
  }

**Comment by phanxgames** [comment]
I figured out the issue:

The set config method must be called before the creation of a new PhanxMysql instance.

Such as:  
```
protected db:PhanxMysql = null;
constructor() {
     PhanxMysql.config = config;
     this.db = new PhanxMysql();
}
```

In your code example above you are setting new PhanxMysql on your protected line, and then the set config is occurring in the constructor after that.

You can solve this with the example given right above or with the following example instead, by passing the config into the constructor directly:

```
protected db = new PhanxMysql(config);
```

It is simply a requirement to set the static config before instance creation (or pass it in directly). I will see about allowing the code to be more flexible in this matter.

I intended on the PhanxMysql.config to be set in the application entry (main.ts) once before any class is initialized, so it can be used in every class in the whole project. That is how I solve this in my projects.

Sorry for the confusion!
